#[cfg(feature = "daemon")]
pub mod audio;
#[cfg(feature = "daemon")]
pub mod awww;
#[cfg(feature = "media")]
pub mod blocks;
#[cfg(feature = "daemon")]
pub mod bridge_preview;
pub mod config;
pub mod database;
pub mod diagnostics;
#[cfg(feature = "daemon")]
pub mod dms;
#[cfg(feature = "daemon")]
pub mod matugen;
#[cfg(feature = "media")]
pub mod media;
#[cfg(feature = "daemon")]
pub mod noctalia;
pub mod observability;
pub mod outputs;
pub mod pack;
#[cfg(feature = "daemon")]
pub mod paper;
pub mod paths;
#[cfg(feature = "daemon")]
pub mod plasma;
#[cfg(feature = "daemon")]
pub mod postprocess;
pub mod process;
#[cfg(feature = "daemon")]
pub mod renderers;
#[cfg(feature = "media")]
pub mod scan;
#[cfg(feature = "daemon")]
pub mod shell_adapter;
#[cfg(feature = "daemon")]
pub mod static_templates;
pub mod synchronization;
#[cfg(feature = "daemon")]
pub mod theme;
#[cfg(feature = "daemon")]
pub mod theme_provider;
#[cfg(feature = "daemon")]
pub mod theme_sink;
#[cfg(feature = "daemon")]
pub mod wallpaper;
#[cfg(feature = "daemon")]
pub mod we;
